[Fix] Fix `fsdp2_load_state_dict` with HSDP (#554)
# What does this PR do?

HSDP is broken on `main` right now, likely after upgrade to torch 2.7.1:


```bash
RuntimeError: ('Found the DeviceMesh have 2 dimensions', 'Optional kwarg `mesh_dim` needs to be specified when device_mesh.ndim > 1
.', 'If you want to get the list of all the ProcessGroups in the DeviceMesh,please use `get_all_groups()` instead.')
```

We switch to using the default process group directly now since that was
the previous behaviour.

---------

Signed-off-by: SumanthRH <sumanthrh@anyscale.com>