[deps] remove numpy from override dependencies (#1178)
numpy does actually need to be < 2.0.0 for checkpointing in
megatron-core currently (although this restriction will be lifted in
megatron-core==0.16.0:
https://github.com/NVIDIA/Megatron-LM/issues/1563#issuecomment-3848532979)

So we cannot allow the flexible resolution that was previously being
used (` "numpy>=1.24.0,<2.3; sys_platform == 'linux'"`).

This caused the following error for checkpointing tests for megatron

```bash
  File "/home/ray/.cache/uv/builds-v0/.tmpfUQqEZ/lib/python3.12/site-packages/megatron/core/dist_checkpointing/validation.py", line 522, in _validate_sharding_for_key_flattened
    expected_size = np.product(local_shape)
                    ^^^^^^^^^^
  File "/home/ray/.cache/uv/builds-v0/.tmpfUQqEZ/lib/python3.12/site-packages/numpy/__init__.py", line 414, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'product'
```

As an alternative solution to #1175, we can override `ml_dtypes` for
python 3.12 to be >= 0.5.0.
<!-- devin-review-badge-begin -->

---

<a href="https://app.devin.ai/review/novasky-ai/skyrl/pull/1178"
target="_blank">
  <picture>
<source media="(prefers-color-scheme: dark)"
srcset="https://static.devin.ai/assets/gh-open-in-devin-review-dark.svg?v=1">
<img
src="https://static.devin.ai/assets/gh-open-in-devin-review-light.svg?v=1"
alt="Open with Devin">
  </picture>
</a>
<!-- devin-review-badge-end -->