[train] Support IPv6 addresses in TCP URL construction (#612)
# Overview
On an IPv6 only stack, we get the following error when parsing ipv6
addresses in `skyrl-train`:
```
(AsyncVLLMInferenceEngine pid=1667, ip=2602:fb33:0:e1:9570::b) (EngineCore_0 pid=2285)
File "workspace/SkyRL/skyrl-train/.venv/lib/python3.12/site-packages/vllm/utils/__init__.py", line 3007, in run_method
  return func(*args, **kwargs)
File "workspace/SkyRL/skyrl-train/skyrl_train/inference_engines/vllm/vllm_engine.py", line 103, in init_weight_update_communicator
  self._model_update_group = init_custom_process_group()
File "workspace/SkyRL/skyrl-train/skyrl_train/distributed/utils.py", line 76, in init_custom_process_group
  store, rank, world_size = next(rendezvous_iterator)
File "/home/ray/anaconda3/lib/python3.12/site-packages/torch/distributed/rendezvous.py", line 216, in _tcp_rendezvous_handler
  if not result.port:
File "/home/ray/anaconda3/lib/python3.12/urllib/parse.py", line 182, in port
  raise ValueError(f"Port could not be cast to integer value as {port!r}: {self.port}")
ValueError: Port could not be cast to integer value as {port!r}: 'f3:03::e1:c6c9::d:52001'
```
PyTorch’s TCP rendezvous handler was passed an unbracketed IPv6 literal
(e.g. f3:03::e1:c6c9::d:52001) as the host:port string. The colon
parsing failed, so the IPv6 address and port got concatenated.

This PR adds a simple utility to check if an address is formatted as
ipv6, and adds the appropriate brackets around it while constructing the
TCP URL.

---------

Signed-off-by: SumanthRH <sumanthrh99@gmail.com>
Co-authored-by: Sumanth R Hegde <39546518+SumanthRH@users.noreply.github.com>
Co-authored-by: gemini-code-assist[bot] <176961590+gemini-code-assist[bot]@users.noreply.github.com>
Co-authored-by: SumanthRH <sumanthrh99@gmail.com>