[Fix][GPU CI] Fix cleanup logic in LoRA test (#443)
# What does this PR do?

fixes the cleanup logic in the LoRA test. 

While executing tests in the same pytest session, we should not call
`xxxRegistry.reset()` unnecessarily because that will clear all
registered functions.

This can affect other tests that execute later that depend on the
registries.

This is the root cause for test failures for `test_save_load_checkpoint`
yesterday and today

```bash
RuntimeError: Engine core initialization failed. See root cause above. Failed core proc(s): {}
FAILED tests/gpu/gpu_ci/test_save_load_checkpoint.py::test_save_load_checkpoint[deepspeed] - AssertionError: invalid policy_loss_type: regular. Must be one of []
FAILED tests/gpu/gpu_ci/test_save_load_checkpoint.py::test_save_load_checkpoint[fsdp] - AssertionError: invalid policy_loss_type: regular. Must be one of []
FAILED tests/gpu/gpu_ci/test_save_load_checkpoint.py::test_save_load_checkpoint[fsdp2] - AssertionError: invalid policy_loss_type: regular. Must be one of []
```

---------

Signed-off-by: SumanthRH <sumanthrh99@gmail.com>